from pathlib import Path
path = Path('api/routers/cards.py')
text = path.read_text(encoding='utf-8').splitlines()
start = None
end = None
for idx,line in enumerate(text):
    if start is None and line.strip() == 'featured_block = ""':
        start = idx
    if start is not None and '# Endere' in line:
        end = idx
        break
if start is None or end is None:
    raise SystemExit('bounds not found')
block = []
block.append('    featured_block = ""')
block.append('')
block.append('    if featured_label and featured_url and featured_enabled:')
block.append('')
block.append('        featured_style = (')
block.append('')
block.append('            f"--featured-start:{feat_start};"')
block.append('')
block.append('            f"--featured-end:{feat_end};"')
block.append('')
block.append('            f"--featured-shadow-rgb:{feat_shadow_rgb};"')
block.append('')
block.append('            f"--featured-text:{feat_text_color};"')
block.append('')
block.append('        )')
block.append('')
block.append('        featured_inner = f"""')
block.append('')
block.append("          <div class='featured-cta__text'>")
block.append('')
block.append("            <span class='featured-cta__eyebrow'>Em destaque</span>")
block.append('')
block.append("            <span class='featured-cta__label'>{html.escape(featured_label)}</span>")
block.append('')
block.append("            <span class='featured-cta__hint'>Toque para continuar</span>")
block.append('')
block.append('          </div>')
block.append('')
block.append("          <span class='featured-cta__icon' aria-hidden='true'>")
block.append('')
block.append("            <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='22' height='22' fill='none' stroke='currentColor' stroke-width='2'>")
block.append('')
block.append("              <path d='M5 12h14'></path>")
block.append('')
block.append("              <path d='M13 6l6 6-6 6'></path>")
block.append('')
block.append('            </svg>')
block.append('')
block.append('          </span>')
block.append('')
block.append('        """')
block.append('')
block.append('        featured_data = f"featured-{html.escape(slug)}"')
block.append('')
block.append('        featured_style_attr = html.escape(featured_style)')
block.append('')
block.append('        if is_owner:')
block.append('')
block.append('            featured_block = f"""')
block.append('')
block.append("        <div class='featured-cta featured-cta--preview' data-cta='{featured_data}' style='{featured_style_attr}' aria-label='Prévia do botão destaque exibida apenas para você.'>")
block.append('')
block.append("          <div class='featured-cta__text'>")
block.append('')
block.append("            <span class='featured-cta__eyebrow'>Em destaque</span>")
block.append('')
block.append("            <span class='featured-cta__label'>{html.escape(featured_label)}</span>")
block.append('')
block.append("            <span class='featured-cta__hint'>Visitantes verão este botão</span>")
block.append('')
block.append('          </div>')
block.append('')
block.append("          <span class='featured-cta__icon' aria-hidden='true'>")
block.append('')
block.append("            <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='22' height='22' fill='none' stroke='currentColor' stroke-width='2'>")
block.append('')
block.append("              <path d='M5 12h14'></path>")
block.append('')
block.append("              <path d='M13 6l6 6-6 6'></path>")
block.append('')
block.append('            </svg>')
block.append('')
block.append('          </span>')
block.append('')
block.append('        </div>')
block.append('')
block.append('        """')
block.append('')
block.append('        else:')
block.append('')
block.append('            featured_block = f"""')
block.append('')
block.append("        <a class='featured-cta' href='{html.escape(featured_url)}' target='_blank' rel='noopener' data-cta='{featured_data}' style='{featured_style_attr}'>")
block.append('')
block.append('          {featured_inner}')
block.append('')
block.append('        </a>')
block.append('')
block.append('        """')
block.append('')
text[start:end] = block
path.write_text('\n'.join(text), encoding='utf-8')
