name = "soomei-router"
main = "worker.js"
compatibility_date = "2024-10-01"

[[kv_namespaces]]
binding = "CARDS"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[queues.producers]]
queue = "taps-queue"
binding = "TAPS"
