name: Release & Deploy

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

concurrency:
  group: prod-deploy
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for release)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    env:
      PROD_PATH: ${{ secrets.PROD_PATH || '/opt/soomei' }}
    steps:
      # <<< ESTE PASSO É ESSENCIAL >>>
      - name: Checkout tag (for deploy)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}   # garante o checkout da tag que disparou o workflow

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 22
          # use bloco multilinha com globs que sempre dão match
          source: |
            ./**
            !.git/**
            !.github/**
            !**/*.md
            !**/.gitignore
          target: ${{ env.PROD_PATH }}
          overwrite: true
          strip_components: 0

      - name: Restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 22
          script: |
            set -e
            cd "${{ env.PROD_PATH }}"
            systemctl restart soomei
            systemctl is-active --quiet soomei && echo "soomei ativo."
            journalctl -u soomei -n 50 --no-pager || true
